package net.rtxyd.fallen.lib.config;

import com.google.gson.annotations.SerializedName;

import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

public class FallenConfig {
    // auto generated by gradle.
    public static final String VERSION = BuildInfo.VERSION;

    @SerializedName("required")
    boolean required;

    @SerializedName("min_version")
    String minVersion;

    @SerializedName("package")
    String pkg;

    @SerializedName("fallen_patches")
    List<String> patches;

    public boolean isRequired() {
        return required;
    }
    public String getMinVersion() {
        return minVersion;
    }
    public String getPackage() {
        return pkg;
    }
    public List<String> getPatches() {
        return Collections.unmodifiableList(patches);
    }

    public boolean versionCheck() {
        String[] vParts = VERSION.split("\\.");
        String[] mParts = minVersion.split("\\.");

        int length = Math.max(vParts.length, mParts.length);
        for (int i = 0; i < length; i++) {
            int v = i < vParts.length ? Integer.parseInt(vParts[i]) : 0;
            int m = i < mParts.length ? Integer.parseInt(mParts[i]) : 0;
            // min_version < version -> true
            if (m < v) return true;
            if (m > v) return false;
        }
        return true;
    }

    public List<String> buildClassNames() {
        return patches.stream().map(s -> pkg + "." + s).collect(Collectors.toList());
    }
}


